version: '3.8'

services:
  oracle-db:
    container_name: oracle-enterprise
    image: container-registry.oracle.com/database/enterprise:19.19.0.0
    restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_SID: ORLCDV
      ORACLE_PDB: WINT
      ORACLE_PWD: "S3nh4Admin01"
      INIT_SGA_SIZE: 8192
      INIT_PGA_SIZE: 2048
      INIT_CPU_COUNT: 4
      INIT_PROCESSES: 900
      ORACLE_EDITION: "enterprise"
      ORACLE_CHARACTERSET: "WE8MSWIN1252"
      ENABLE_ARCHIVELOG: "true"
      ENABLE_FORCE_LOGGING: "true"
      ENABLE_TCPS: "true"
    volumes:
      - ./dados/oradata:/opt/oracle/oradata
      - ./scripts:/scripts:rw
      - ./dump:/dump:rw
