CREATE BIGFILE TABLESPACE TS_DADOS DATAFILE '/opt/oracle/oradata/ORLCDV/WINTVEL/TS_DADOS.dbf'
    SIZE 100G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE TS_INDICE DATAFILE '/opt/oracle/oradata/ORLCDV/WINTVEL/TS_INDICE.dbf'
    SIZE 3G AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED SEGMENT SPACE MANAGEMENT AUTO;

ALTER SYSTEM SET CURSOR_SHARING=EXACT SCOPE=BOTH;
ALTER SYSTEM SET JOB_QUEUE_PROCESSES=10 SCOPE=BOTH;

EXIT;
