-- Privilegio do schema Winthor. GRANT e idempotente no Oracle.
-- Identificadores com $ (v_$session, obj$) nao sao interpolados.

WHENEVER SQLERROR EXIT SQL.SQLCODE

GRANT CONNECT, RESOURCE TO ${SCHEMA_DESTINO};
GRANT CREATE SESSION TO ${SCHEMA_DESTINO} WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO ${SCHEMA_DESTINO};
GRANT CREATE TABLE TO ${SCHEMA_DESTINO};
GRANT CREATE VIEW TO ${SCHEMA_DESTINO};
GRANT CREATE PROCEDURE TO ${SCHEMA_DESTINO};
GRANT CREATE USER TO ${SCHEMA_DESTINO};
GRANT SELECT ON DBA_TABLESPACES TO ${SCHEMA_DESTINO} WITH GRANT OPTION;
GRANT ALTER SESSION TO ${SCHEMA_DESTINO};
GRANT ALTER USER TO ${SCHEMA_DESTINO};
GRANT CREATE ROLE TO ${SCHEMA_DESTINO};
GRANT CREATE SEQUENCE TO ${SCHEMA_DESTINO};
GRANT CREATE SYNONYM TO ${SCHEMA_DESTINO};
GRANT CREATE TRIGGER TO ${SCHEMA_DESTINO};
GRANT CREATE TYPE TO ${SCHEMA_DESTINO};
GRANT CREATE DATABASE LINK TO ${SCHEMA_DESTINO};
GRANT DROP ANY ROLE TO ${SCHEMA_DESTINO};
GRANT DROP USER TO ${SCHEMA_DESTINO};
GRANT DEBUG ANY PROCEDURE TO ${SCHEMA_DESTINO};
GRANT DEBUG CONNECT SESSION TO ${SCHEMA_DESTINO};
GRANT QUERY REWRITE TO ${SCHEMA_DESTINO};
GRANT SELECT ON sys.v_$session TO ${SCHEMA_DESTINO};
GRANT SELECT ON sys.v_$sysstat TO ${SCHEMA_DESTINO};
GRANT SELECT ON sys.v_$sesstat TO ${SCHEMA_DESTINO};
GRANT SELECT ON sys.v_$statname TO ${SCHEMA_DESTINO};
GRANT SELECT ON dba_roles TO ${SCHEMA_DESTINO};
GRANT SELECT ON dba_users TO ${SCHEMA_DESTINO};
GRANT SELECT ON dba_free_space TO ${SCHEMA_DESTINO} WITH GRANT OPTION;
GRANT SELECT ON dba_data_files TO ${SCHEMA_DESTINO} WITH GRANT OPTION;
GRANT SELECT ON dba_temp_files TO ${SCHEMA_DESTINO} WITH GRANT OPTION;
GRANT SELECT ON dba_sys_privs TO ${SCHEMA_DESTINO};
GRANT SELECT ON dba_tab_privs TO ${SCHEMA_DESTINO};
GRANT SELECT ON dba_role_privs TO ${SCHEMA_DESTINO};
GRANT EXECUTE ON dbms_session TO ${SCHEMA_DESTINO};
GRANT SELECT ON gv_$session TO ${SCHEMA_DESTINO};
GRANT SELECT ON v_$database TO ${SCHEMA_DESTINO};
GRANT SELECT ON sys.obj$ TO ${SCHEMA_DESTINO};
GRANT SELECT ON sys.view$ TO ${SCHEMA_DESTINO};
GRANT SELECT ON sys.user$ TO ${SCHEMA_DESTINO};
ALTER USER ${SCHEMA_DESTINO} QUOTA UNLIMITED ON ${TS_DADOS};
ALTER USER ${SCHEMA_DESTINO} QUOTA UNLIMITED ON ${TS_INDICE};
ALTER USER ${SCHEMA_DESTINO} QUOTA 0m ON SYSTEM;
GRANT CREATE MATERIALIZED VIEW TO ${SCHEMA_DESTINO};
GRANT GLOBAL QUERY REWRITE TO ${SCHEMA_DESTINO};
GRANT SELECT ANY TABLE TO ${SCHEMA_DESTINO};
GRANT UNLIMITED TABLESPACE TO ${SCHEMA_DESTINO};
GRANT SELECT ON v_$database TO PUBLIC;
GRANT SELECT ON gv_$session TO PUBLIC;
GRANT CREATE ANY MATERIALIZED VIEW TO ${SCHEMA_DESTINO};
ALTER USER ${SCHEMA_DESTINO} QUOTA 0m ON users;
CREATE OR REPLACE DIRECTORY DUMP_DIR AS '${DUMP_DIR}';
GRANT READ, WRITE ON DIRECTORY DUMP_DIR TO system;
COMMIT;
EXIT;
